<div class="container">
    <h1><?php echo $title; ?></h1>
    <hr>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($contacts as $contact): ?>
                <tr>
                    <td><?php echo $contact->name; ?></td>
                    <td><?php echo $contact->email; ?></td>
                    <td><?php echo $contact->phone; ?></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div> <!-- End container -->