<div class="container">
    <?php echo $this->getContent() ?>
    
    <div class="row">
       <div class="col-md-6 col-md-offset-3">
            
            <?php echo $this->tag->linkTo(array(
                'contacts/index', 
                '<i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> Go back',
                'class' => 'btn btn-default btn-add-contact'
            )) ?> 
            
            <h1><?php echo $title; ?></h1>
            <hr>
            
            <?php echo $this->tag->form('contacts/create') ?>
        
            <div class="form-group">
                <label for="name">Name</label>
                <?php echo $this->tag->textField(array('name', 
                     'class' => 'form-control',
                     'id'    => 'name',
                     'placeholder' => 'Name of the contact')) 
                ?>
            </div>
            
            <div class="form-group">
                <label for="phone">Phone</label>
                <?php echo $this->tag->textField(array('phone', 
                     'class' => 'form-control',
                     'id'    => 'phone',
                     'placeholder' => 'Phone number')) 
                ?>
            </div>
            
            <div class="form-group">
                <label for="email">Email</label>
                <?php echo $this->tag->textField(array('email', 
                     'class' => 'form-control',
                     'id'    => 'email',
                     'placeholder' => 'Email address')) 
                ?>
            </div>
            
        
            <div class="text-center">
                <?php echo $this->tag->submitButton(array('Create new Contact', 
                     'class' => 'btn btn-primary',
                     'id'    => 'btn-submit-new-contact')) 
                ?>
            </div> <!-- End text-center -->
        </form>
        
        </div> <!-- End col-md-6 col-md-offset-3 --> 
    </div> <!-- End row -->
</div> <!-- End container -->